# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create mgmt 
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/xenial64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.provider "virtualbox" do |vb|
      end

config.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
 config.vm.provision :shell, path: "install-ruby.sh", args: "1.9.3", privileged: false
 config.vm.provision :shell, path: "install-ruby.sh", args: "2.0.0 rails haml", privileged: false
  end
end
