Vagrant.configure('2') do |config|
  # -- snipped --
  config.vm.provision :shell do |s|
    s.path = 'vagrant/provision.sh'
  end
  config.vm.synced_folder '.', '/home/vagrant/myapp'
  # -- snipped --
end